import { Auth0Provider, useAuth0 } from "@auth0/auth0-react";
import LoginButton, { Profile } from "./_login-logout";
import "../styles/globals.css";
import "antd/dist/antd.css"; // or 'antd/dist/antd.less'
import Layout, { Content, Footer } from "antd/lib/layout/layout";
import { Image, PageHeader } from "antd";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NoSSR from "react-no-ssr";

function MyApp({ Component, pageProps }) {
  return (
    <Auth0Provider
      domain="lucas-bibiano.us.auth0.com"
      clientId="QBTsFhQP6xuwUapsuEqoZxub9DohRs2T"
      redirectUri={process.env.URL}
      audience="https://lucas-bibiano.us.auth0.com/api/v2/"
      scope="read:current_user update:current_user_metadata"
      cacheLocation="localstorage"
    >
      <Head>
        <title>IOT - Gerenciamento de Dispositivos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeader
          className="site-page-header-responsive"
          onBack={() => window.history.back()}
          title="IOT"
          subTitle="Gerenciamento dos dispositivos"
          extra={[<Profile key={"pf01"} />]}
        >
          <h1 className={styles.title}>Bem Vindo!</h1>
          <h1 className={styles.title}>
            {" "}
            <LoginButton />
          </h1>
        </PageHeader>
        <NoSSR>
          <Content>
            <Component {...pageProps} />
          </Content>
        </NoSSR>
        <Footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Footer>
      </Layout>
    </Auth0Provider>
  );
}

export default MyApp;
